# Generated by Django 6.0 on 2026-01-21 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'localization',
                'verbose_name_plural': 'localizations',
                'indexes': [models.Index(fields=['city'], name='offices_loc_city_bd208e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=16, null=True)),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='offices.localization')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
                'indexes': [models.Index(fields=['localization'], name='offices_off_localiz_332d7e_idx')],
                'unique_together': {('localization', 'room_number')},
            },
        ),
    ]
