# Generated by Django 6.0.5 on 2026-05-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_timestamp'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent_phone',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-creation_timestamp'], name='notif_user_created_idx'),
        ),
    ]
