services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - docker/backend.dev.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    env_file: docker/postgres.dev.env
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build: ./backend
    container_name: celery-worker
    command: celery -A stoms worker --loglevel=info
    restart: always
    environment:
      SKIP_STARTUP_TASKS: "1"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - docker/backend.dev.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A stoms beat --loglevel=info
    restart: always
    environment:
      SKIP_STARTUP_TASKS: "1"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - docker/backend.dev.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
      - redis


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev

  storybook:
    build: ./frontend
    container_name: storybook
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn storybook

volumes:
  postgres_data: