
services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - docker/backend.dev.env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file: docker/postgres.dev.env
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev

  storybook:
    build: ./frontend
    container_name: storybook
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn storybook

volumes:
  postgres_data: