# Generated by Django 6.0.5 on 2026-05-30 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('therapist_availability', '0001_move_therapist_from_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='therapist',
        ),
        migrations.AddField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapist', to='offices.office'),
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('BASE', 'Stały grafik tygodniowy'), ('INCLUSION', 'Dodatkowa dostępność'), ('EXCLUSION', 'Wykluczenie dostępności')], default='BASE', max_length=20)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='therapist_availability.therapist')),
            ],
            options={
                'verbose_name': 'Blok dostępności',
                'verbose_name_plural': 'Bloki dostępności',
                'ordering': ['day_of_week', 'specific_date', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'type', 'day_of_week'], name='therapist_a_therapi_42f4f6_idx'), models.Index(fields=['therapist', 'type', 'specific_date'], name='therapist_a_therapi_6a4e7b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('day_of_week__isnull', False), ('specific_date__isnull', True), ('type', 'BASE')), models.Q(('day_of_week__isnull', True), ('specific_date__isnull', False), ('type__in', ['INCLUSION', 'EXCLUSION'])), _connector='OR'), name='availability_block_type_fields_xor')],
            },
        ),
    ]
