# Generated by Django 6.0.5 on 2026-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_availability', '0002_remove_therapist_therapist_therapist_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availabilityblock',
            name='availability_block_type_fields_xor',
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_of_week__isnull', False), ('specific_date__isnull', True), ('type', 'BASE')), models.Q(('day_of_week__isnull', True), ('specific_date__isnull', False), ('type__in', ['INCLUSION', 'EXCLUSION'])), _connector='OR'), name='availability_block_type_fields_constraint'),
        ),
        migrations.AlterModelTable(
            name='therapist',
            table=None,
        ),
    ]
