# Generated by Django 6.0 on 2026-01-22 18:34

import django.db.models.deletion
import recurrence.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_patient_date_of_birth_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('duration_time_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_periodic', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'appointment type',
                'verbose_name_plural': 'appointment types',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series', to='users.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series', to='users.therapist')),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series', to='reservations.appointmenttype')),
            ],
            options={
                'verbose_name': 'appointment series',
                'verbose_name_plural': 'appointment series',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('appointment_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='reservations.appointmentseries')),
            ],
        ),
    ]
