# Generated by Django 6.0 on 2026-01-26 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttype',
            options={'verbose_name': 'Rodzaj wizyty', 'verbose_name_plural': 'Rodzaje wizyt'},
        ),
        migrations.RemoveField(
            model_name='appointmentseries',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Zaplanowana'), ('COMPLETED', 'Zakończona'), ('CANCELED', 'Anulowana')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentseries',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktywna'), ('ENDED', 'Zakończona'), ('CANCELED', 'Anulowana')], default='ACTIVE', max_length=20),
        ),
    ]
