# Generated by Django 6.0.5 on 2026-05-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_is_active_alter_patient_user_and_more'),
        ('reservations', '0003_retarget_patient_therapist_models'),
        ('therapist_availability', '0002_remove_therapist_therapist_therapist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='therapist_availability.therapist'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='reservations.appointmentseries'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['therapist', 'appointment_date', 'status'], name='appt_therapist_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='appt_patient_date_idx'),
        ),
    ]
