# Generated by Django 6.0 on 2026-01-24 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityblock',
            options={'ordering': ['day_of_week', 'specific_date', 'start_time'], 'verbose_name': 'Blok dostępności', 'verbose_name_plural': 'Bloki dostępności'},
        ),
        migrations.AlterField(
            model_name='availabilityblock',
            name='availability_type',
            field=models.CharField(choices=[('WEEKLY', 'Blok tygodniowy'), ('INCLUSION', 'Blok dodatkowych godzin'), ('EXCLUSION', 'Blok wyjątkowego braku godzin')], default='WEEKLY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['therapist', 'availability_type'], name='scheduling__therapi_72e1d0_idx'),
        ),
    ]
