@startuml Speech Therapy Office Management System (sTOMs)

hide empty methods
hide circle

'---------------
' Profiles
'---------------

class User {
    id : uuid
--
    first_name : varchar(64)
    surname : varchar(64)
    email : varchar(255) <<UNIQUE>>
    password_hash : varchar(128) <<NOT NULL>>
    user_type : varchar(10) [PATIENT, THERAPIST]
    is_active : varchar
}


class Therapist {
    id : uuid
--
    user_id : uuid <<FK>>
    default_availability : uuid <<FK>>
}

class Patient {
    id : uuid
--
    user_id : uuid <<FK>>
}

User "1" -- "1" Therapist : is_a
User "1" -- "1" Patient : is_a


'---------------
' Therapy and Scheduling
'---------------

class AppointmentTypes {
    id : uuid
--
    name : varchar(100)
    duration_time_minutes : int
    price : numeric(5,2)
}

class TherapistAvailability {
    id : uuid
--
    therapist_id : uuid <<FK>>
    availability : json
}


class Appointment {
    id : uuid
--
    patient_id : uuid <<FK>>
    therapist_id : uuid <<FK>>
    appointment_type_id : uuid <<FK>>
    start_time : timestamp
    end_time : timestamp
    status : varchar(10) [SCHEDULED, CONFIRMED, COMPLETED, CANCELED]
    notes : text <<NULLable>>
}

Patient "1" -- "0..*" Appointment : books
Therapist "1" -- "0..*" Appointment : conducts
AppointmentTypes "1" -- "0..*" Appointment : defines type


'---------------
' Home Assignments
'---------------

class Exercise {
    id : uuid
--
    title : varchar(255)
    description : text
    media_url : url
    created_by_id : uuid <<FK>>

}


class Assignment {
    id : uuid
--
    client_id : uuid <<FK>>
    therapist_id : uuid <<FK>>
    custom_instructions : text
    due_date : date
}

class AssignmentExercise {
    id : uuid
--
    assignment_id : uuid <<FK>>
    exercise_id : uuid <<FK>>
    sequence_order : int
    custom_instructions : text <<NULLable>>
    sets_reps : varchar(50) <<NULLable>>
    is_completed : boolean

}

Therapist "1" -- "0..*" Assignment : creates
Patient "1" -- "0..*" Assignment : receives

Assignment "1" *-- "1..*" AssignmentExercise : composed_of
Exercise "1" -- "0..*" AssignmentExercise : included_in

@enduml
