# Generated by Django 6.0 on 2026-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('THERAPIST', 'Therapist')], default='CLIENT', max_length=20),
        ),
    ]
