# Generated by Django 6.0 on 2026-01-17 16:50

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_verification_token_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='last name'),
        ),
    ]
