# Generated by Django 6.0 on 2026-01-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('users', '0005_alter_patient_date_of_birth_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapists', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
