# Generated by Django 6.0 on 2026-01-23 21:51

import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_therapist_office_alter_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-is_primary', 'last_name', 'first_name'], 'verbose_name': 'Pacjent', 'verbose_name_plural': 'Pacjenci'},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeuci'},
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Określa czy pacjent przypisany do klienta określa samego siebie', verbose_name='Pacjent główny'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapist',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adres email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+48)?\\d{9}$', 'Invalid phone number')], verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Klient'), ('THERAPIST', 'Terapeuta')], default='CLIENT', max_length=20, verbose_name='Rola'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[users.validators.validate_patient_age], verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('user', 'first_name', 'last_name', 'date_of_birth')},
        ),
    ]
