# Generated by Django 6.0 on 2026-01-24 22:58

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appuser_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=64, validators=[users.validators.validate_only_letters], verbose_name='last name'),
        ),
    ]
