# Generated by Django 6.0.5 on 2026-06-04 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_move_patient_and_therapist_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+48\\d{9}$', 'Numer telefonu musi zaczynać się od +48 i mieć 9 cyfr.')], verbose_name='Numer telefonu'),
        ),
    ]
